 # def f1():
#     s = "I Love Navgurukul"
#     print(s)
# f1()


# def first_function():
#     s = 'I love India'
#     def second_function():
#         print(s)     
#     second_function()
# first_function() 



# def first_function():
#     s = 'I love India'
#     def second_function():
#         s = "MY NAME IS JACK"
#         print(s)     
#     second_function()
#     print(s)    

# first_function()


#eligible_for_vote name ka function likho jo ki
#  user ko bataye ki vo (he/she) vote de sakta hai ya nahi.
#  ( Consider minimum age of voting to be 18. ) Example:- Agar user
#  input me 18 se kam deta hai to “not eligible “ print kare aur agar user 18 ya 18 
# se jyaada input kare to “you are eligible” print kare. Input:- Output :-


# def vote():
#     if a>=18:
#         print("you are eligible")
#     else:
#         print("you are not eligible")
# a=int(input("enter the age"))
# vote()
    